version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jp3_db
    volumes:
      - mysql_data:/var/lib/mysql
    # --- NUEVA SECCIÓN ---
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: rootpassword
      DB_NAME: jp3_db
    # --- LÍNEA MODIFICADA ---
    depends_on:
      db:
        condition: service_healthy

volumes:
  mysql_data: